### ISSUE TITLE
strange behaviour with the new version of voms-client-cpp in epel testing

### ISSUE THREAD

**Issue by andrea-manzi** [cernops/puppet-voms#3]
Hi,
i have a strange behaviour in my VMs where i use puppet-voms to configure voms-clients, started with the upgrade to epel-testing of the latest voms-clients-cpp

https://admin.fedoraproject.org/updates/voms-2.0.12-3.el6

with this update, voms-clients is now a virtual package provided by voms-clients-cpp.

and at every puppet run i see this executed:

Debug: Executing '/usr/bin/yum -d 0 -e 0 -y list voms-clients'
Debug: Package[voms-clients](provider=yum): Ensuring => present
Debug: Executing '/usr/bin/yum -d 0 -e 0 -y install voms-clients'
Notice: /Stage[main]/Voms::Install/Package[voms-clients]/ensure: created
Debug: /Stage[main]/Voms::Install/Package[voms-clients]: The container Class[Voms::Install] will propagate my refresh event

i don't know if the problem is related to the fact that being a virtual package is not installed on the system so puppet tries to install it everytime..

thanks
cheers
Andrea

**Comment by traylenator** [comment]
Indeed the package has changed name effectivly from voms-clients to voms-clients-cpp.

Virtual package support names only starts to come in with newer versions of puppet, to new to
expect people to have.

We shall create a new release once packages are deployed but you should be able to with this pull request set

``` yaml
voms::install::vomsclient:
  - voms-clinet-cpp
  - voms-client-java

to install the new package names. All a bit untested but should work.

Steve.
```

**Comment by andrea-manzi** [comment]
Hi Steve,
i just realized that the version of puppet-voms on git-hub is quite old, and the one at cern already have the voms-client package configurable

https://git.cern.ch/web/it-puppet-module-voms.git/blob/refs/heads/qa:/code/manifests/params.pp

so i have added to my hiera conf

voms::params::voms_clientpkgs:
- voms-clients-cpp

but still see at every puppet run the log

Notice: /Stage[main]/Voms::Install/Package[voms-clients]/ensure: created

**Comment by traylenator** [comment]
With the CERN version of the module:

``` yaml
voms::install::clientpkgs:
  - voms-clients-cpp
```

I will probably drop that pull request and actually do the update on CERNOPS which is long overdue.
